//LOGED IN TYPES
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
// FETCH EMPLOYEES TYPES
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const HANDLE_ERROR = 'HANDLE_ERROR';